#!/usr/bin/env node
// Builds the content admin (Sveltia CMS) into out/admin/:
//  - bundles the CMS from node_modules, so no code or fonts load from third-party CDNs,
//  - hashes the entry file name, because nginx serves .js files with a year-long cache,
//  - generates config.yml from the content schemas (scripts/cms-config.mjs).
// ADMIN_BACKEND=test-repo builds an in-memory variant for local checks; never deploy it.
import { build } from "esbuild";
import { cpSync, existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { cmsConfig } from "./cms-config.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const outDir = process.env.ADMIN_OUT ?? join(root, "out/admin");
const cmsDir = join(outDir, "cms");
const packageDir = join(root, "node_modules/@sveltia/cms/npm");

const fail = (message) => {
  console.error(`build-admin: ${message}`);
  process.exit(1);
};

rmSync(outDir, { recursive: true, force: true });

const entryPoint = "admin/entry.mjs";
const result = await build({
  absWorkingDir: root,
  entryPoints: { "sveltia-cms": join(root, entryPoint) },
  bundle: true,
  format: "esm",
  splitting: true,
  minify: true,
  target: "es2022",
  outdir: cmsDir,
  entryNames: "[name]-[hash]",
  chunkNames: "c-[hash]",
  metafile: true,
  logLevel: "warning",
});

// Dynamically imported chunks are listed as entry points too, so match the real one.
const entry = Object.entries(result.metafile.outputs).find(
  ([, output]) => output.entryPoint === entryPoint,
)?.[0];
if (!entry) fail("esbuild produced no entry file");

cpSync(join(packageDir, "assets"), join(cmsDir, "assets"), {
  recursive: true,
  filter: (src) => !src.endsWith(".map"),
});

// Sveltia's own chunks sit one directory below its entry and resolve "../assets/"; the bundle
// is flat, so every asset URL is rewritten to the sibling folder and must exist there.
const missing = [];
for (const file of readdirSync(cmsDir).filter((f) => f.endsWith(".js"))) {
  const path = join(cmsDir, file);
  const code = readFileSync(path, "utf8");
  const fixed = code.replace(/(["'`])\.\.\/assets\//g, "$1./assets/");
  if (fixed !== code) writeFileSync(path, fixed);
  for (const [, name] of fixed.matchAll(/["'`](?:\.\/)?assets\/([\w.-]+)["'`]/g)) {
    if (!existsSync(join(cmsDir, "assets", name))) missing.push(`${file} -> assets/${name}`);
  }
}
if (missing.length > 0) fail(`asset references without a file:\n  ${missing.join("\n  ")}`);

const template = readFileSync(join(root, "admin/index.html"), "utf8");
if (template.split("__CMS_ENTRY__").length !== 2) fail("admin/index.html must contain __CMS_ENTRY__ exactly once");
writeFileSync(join(outDir, "index.html"), template.replace("__CMS_ENTRY__", `/admin/cms/${basename(entry)}`));

const backend = process.env.ADMIN_BACKEND === "test-repo" ? { name: "test-repo" } : undefined;
writeFileSync(
  join(outDir, "config.yml"),
  `# Generated by scripts/build-admin.mjs from src/content/schema.ts – do not edit by hand.\n` +
    `${JSON.stringify(cmsConfig({ backend }), null, 2)}\n`,
);

const files = readdirSync(cmsDir, { recursive: true }).filter((f) => statSync(join(cmsDir, f)).isFile());
const bytes = files.reduce((sum, f) => sum + statSync(join(cmsDir, f)).size, 0);
console.log(
  `build-admin: ${files.length} files (${(bytes / 1048576).toFixed(1)} MB), entry ${basename(entry)}` +
    (backend ? ", TEST backend" : ""),
);
